/**
 * App
 */
export const SHOW_ALERT = 'SHOW_ALERT';
export const SHOW_TOAST = 'SHOW_TOAST';
export const SET_ALERT_MESSAGE = 'SET_ALERT_MESSAGE';
export const SET_ALERT_SUCCESS = 'SET_ALERT_SUCCESS';
export const SET_TOAST_MESSAGE = 'SET_TOAST_MESSAGE';

/**
 * Search
 */
export const SET_SEARCH_NAV_KEYWORDS_VALUE = 'SET_SEARCH_NAV_KEYWORDS_VALUE';
export const SET_SEARCH_SUGGESTIONS_VALUE = 'SET_SEARCH_SUGGESTIONS_VALUE';
export const SET_SEARCH_SUGGESTIONS_SHOW_STATUS = 'SET_SEARCH_SUGGESTIONS_SHOW_STATUS';
export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS';

/**
 * User
 */
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_USER_LOGIN_STATUS = 'SET_USER_LOGIN_STATUS';
export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_MERCHANT_DATA = 'GET_MERCHANT_DATA';

/**
 * Review
 */
export const GET_REVIEW_DATA = 'GET_REVIEW_DATA';

/**
 * Restaurant
 */
export const GET_RESTAURANT_DATA = 'GET_RESTAURANT_DATA';
export const GET_RESTAURANT_DATA_BY_SKU = 'GET_RESTAURANT_DATA_BY_SKU';
export const GET_RESTAURANT_MENU = 'GET_RESTAURANT_MENU';
export const GET_RESTAURANT_MENU_BY_ID = 'GET_RESTAURANT_MENU_BY_ID';
export const REMOVE_RESTAURANT_MENU = 'REMOVE_RESTAURANT_MENU';

/**
 * Journey / Itinerary
 */
export const GET_JOURNEY_DATA = 'GET_JOURNEY_DATA';
export const REMOVE_ITINERARY = 'REMOVE_ITINERARY';

/**
 * Ticket
 */
export const GET_TICKET_DATA = 'GET_TICKET_DATA';

/**
 * Gallery
 */
export const GET_GALLERY_DATA = 'GET_GALLERY_DATA';
export const REMOVE_GALLERY_PHOTO = 'REMOVE_GALLERY_PHOTO';
