/**
 * App
 */
export const SHOW_ALERT = 'SHOW_ALERT';
export const SHOW_TOAST = 'SHOW_TOAST';
export const SET_ALERT_MESSAGE = 'SET_ALERT_MESSAGE';
export const SET_ALERT_SUCCESS = 'SET_ALERT_SUCCESS';
export const SET_TOAST_MESSAGE = 'SET_TOAST_MESSAGE';
export const SET_IMAGE_PREVIEW = 'SET_IMAGE_PREVIEW';

/**
 * Search
 */
export const SET_SEARCH_NAV_KEYWORDS_VALUE = 'SET_SEARCH_NAV_KEYWORDS_VALUE';
export const SET_SEARCH_SUGGESTIONS_VALUE = 'SET_SEARCH_SUGGESTIONS_VALUE';
export const SET_SEARCH_SUGGESTIONS_SHOW_STATUS = 'SET_SEARCH_SUGGESTIONS_SHOW_STATUS';
export const SET_SEARCH_WISATA_RESULTS = 'SET_SEARCH_WISATA_RESULTS';
export const SET_SEARCH_RESTAURANT_RESULTS = 'SET_SEARCH_RESTAURANT_RESULTS';

/**
 * Authentication
 */
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_USER_SKU = 'SET_USER_SKU';
export const SET_USER_LOGIN_STATUS = 'SET_USER_LOGIN_STATUS';
export const SET_USER_ROLE = 'SET_USER_ROLE';
export const SET_USER_IMAGE = 'SET_USER_IMAGE';
export const SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED';

/**
 * User
 */
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_USER_DATA_BY_SKU = 'SET_USER_DATA_BY_SKU';
export const SET_USER_ACTIVE = 'SET_USER_ACTIVE';
export const SET_USER_BLOCKED = 'SET_USER_BLOCKED';

/**
 * Merchant
 */
export const SET_MERCHANT_DATA = 'SET_MERCHANT_DATA';
export const SET_MERCHANT_DATA_BY_SKU = 'SET_MERCHANT_DATA_BY_SKU';

/**
 * Admin
 */
export const SET_ADMIN_DATA = 'SET_ADMIN_DATA';

/**
 * Review
 */
export const SET_REVIEW_DATA = 'SET_REVIEW_DATA';
export const SET_REVIEW_INFO = 'SET_REVIEW_INFO';

/**
 * Restaurant
 */
export const SET_RESTAURANT_BISTRO_TYPE = 'SET_RESTAURANT_BISTRO_TYPE';
export const SET_RESTAURANT_DATA = 'SET_RESTAURANT_DATA';
export const SET_RESTAURANT_DATA_BY_SKU = 'SET_RESTAURANT_DATA_BY_SKU';
export const SET_RESTAURANT_MENU = 'SET_RESTAURANT_MENU';
export const SET_RESTAURANT_MENU_BY_ID = 'SET_RESTAURANT_MENU_BY_ID';
export const SET_RESTAURANT_REVIEW = 'SET_RESTAURANT_REVIEW';
export const REMOVE_RESTAURANT_MENU = 'REMOVE_RESTAURANT_MENU';

/**
 * Journey / Itinerary
 */
export const SET_JOURNEY_DATA = 'SET_JOURNEY_DATA';
export const SET_JOURNEY_DATA_BY_SKU = 'SET_JOURNEY_DATA_BY_SKU';
export const SET_JOURNEY_DATA_BY_MERCHANT_SKU = 'SET_JOURNEY_DATA_BY_MERCHANT_SKU';
export const SET_JOURNEY_REVIEW = 'SET_JOURNEY_REVIEW';
export const REMOVE_ITINERARY = 'REMOVE_ITINERARY';

/**
 * Ticket
 */
export const SET_TICKET_DATA = 'SET_TICKET_DATA';
export const SET_TICKET_BY_SKU = 'SET_TICKET_BY_SKU';
export const SET_TICKET_BY_USER = 'SET_TICKET_BY_USER';
export const SET_TICKET_BY_MERCHANT = 'SET_TICKET_BY_MERCHANT';
export const SET_TICKET_RESTAURANT_BY_MERCHANT = 'SET_TICKET_RESTAURANT_BY_MERCHANT';
export const SET_TICKET_ITINERARY_BY_MERCHANT = 'SET_TICKET_ITINERARY_BY_MERCHANT';
export const SET_TICKET_RESTAURANT = 'SET_TICKET_RESTAURANT';
export const SET_TICKET_JOURNEY = 'SET_TICKET_JOURNEY';
export const SET_TICKET_PROMOTION = 'SET_TICKET_PROMOTION';
export const REMOVE_TICKET = 'REMOVE_TICKET';

/**
 * Gallery
 */
export const SET_GALLERY_DATA = 'SET_GALLERY_DATA';
export const SET_GALLERY_PHOTO = 'SET_GALLERY_PHOTO';
export const REMOVE_GALLERY_PHOTO = 'REMOVE_GALLERY_PHOTO';

/**
 * Tour Guide
 */
export const SET_TOUR_GUIDE_DATA = 'SET_TOUR_GUIDE_DATA';
export const SET_TOUR_GUIDE_DATA_BY_SKU = 'SET_TOUR_GUIDE_DATA_BY_SKU';
export const SET_TOUR_GUIDE_REVIEW = 'SET_TOUR_GUIDE_REVIEW';
export const REMOVE_TOUR_GUIDE = 'REMOVE_TOUR_GUIDE';

/**
 * Order
 */
export const SET_ORDER_DATA = 'SET_ORDER_DATA';
export const SET_FILTERED_ORDER_DATA = 'SET_FILTERED_ORDER_DATA';
export const SET_APPROVED_ORDER_DATA = 'SET_APPROVED_ORDER_DATA';
export const SET_REJECTED_ORDER_DATA = 'SET_REJECTED_ORDER_DATA';
export const SET_ORDER_DATA_BY_SKU = 'SET_ORDER_DATA_BY_SKU';
export const SET_PAYMENT_BY_SKU = 'SET_PAYMENT_BY_SKU';
export const SET_ORDER_TOTAL = 'SET_ORDER_TOTAL';
export const SET_CART_TOTAL = 'SET_CART_TOTAL';
export const SET_CART_DATA = 'SET_CART_DATA';
export const SET_CART_DATA_QUANTITY = 'SET_CART_DATA_QUANTITY';
export const SET_ACCEPTED_PAYMENT_DATA = 'SET_ACCEPTED_PAYMENT_DATA';
export const SET_WAITING_PAYMENT_DATA = 'SET_WAITING_PAYMENT_DATA';
export const SET_CANCELLED_PAYMENT_DATA = 'SET_CANCELLED_PAYMENT_DATA';
export const SET_MERCHANT_ORDER_DATA = 'SET_MERCHANT_ORDER_DATA';
export const SET_MERCHANT_ITINERARY_ORDER = 'SET_MERCHANT_ITINERARY_ORDER';
export const SET_MERCHANT_RESTAURANT_ORDER = 'SET_MERCHANT_RESTAURANT_ORDER';
export const REMOVE_ORDER = 'REMOVE_ORDER';

/**
 * Location
 */
export const SET_LOCATION_DATA = 'SET_LOCATION_DATA';
export const SET_LOCATION_KEYWORD = 'SET_LOCATION_KEYWORD';
export const SET_LOCATION = 'SET_LOCATION';
export const SET_LOCATION_OPEN = 'SET_LOCATION_OPEN';

/**
 * Schedule
 */
export const SET_SCHEDULE = 'SET_SCHEDULE';
export const SET_NEW_SCHEDULE = 'SET_NEW_SCHEDULE';
export const SET_NEW_SCHEDULE_DETAIL = 'SET_NEW_SCHEDULE_DETAIL';
export const SET_SELECTED_DATE = 'SET_SELECTED_DATE';
export const CLEAR_NEW_SCHEDULE = 'CLEAR_NEW_SCHEDULE';
