/**
 * App
 */
export const SHOW_ALERT = 'SHOW_ALERT';
export const SHOW_TOAST = 'SHOW_TOAST';
export const SET_ALERT_MESSAGE = 'SET_ALERT_MESSAGE';
export const SET_ALERT_SUCCESS = 'SET_ALERT_SUCCESS';
export const SET_TOAST_MESSAGE = 'SET_TOAST_MESSAGE';

/**
 * Search
 */
export const SET_SEARCH_NAV_KEYWORDS_VALUE = 'SET_SEARCH_NAV_KEYWORDS_VALUE';
export const SET_SEARCH_SUGGESTIONS_VALUE = 'SET_SEARCH_SUGGESTIONS_VALUE';
export const SET_SEARCH_SUGGESTIONS_SHOW_STATUS = 'SET_SEARCH_SUGGESTIONS_SHOW_STATUS';
export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS';

/**
 * User
 */
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_USER_LOGIN_STATUS = 'SET_USER_LOGIN_STATUS';
export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_MERCHANT_DATA = 'GET_MERCHANT_DATA';
export const GET_USER_ACTIVE = 'GET_USER_ACTIVE';
export const GET_USER_BLOCKED = 'GET_USER_BLOCKED';

/**
 * Review
 */
export const GET_REVIEW_DATA = 'GET_REVIEW_DATA';
export const GET_REVIEW_INFO = 'GET_REVIEW_INFO';

/**
 * Restaurant
 */
export const GET_RESTAURANT_DATA = 'GET_RESTAURANT_DATA';
export const GET_RESTAURANT_DATA_BY_SKU = 'GET_RESTAURANT_DATA_BY_SKU';
export const GET_RESTAURANT_MENU = 'GET_RESTAURANT_MENU';
export const GET_RESTAURANT_MENU_BY_ID = 'GET_RESTAURANT_MENU_BY_ID';
export const GET_RESTAURANT_REVIEW = 'GET_RESTAURANT_REVIEW';
export const REMOVE_RESTAURANT_MENU = 'REMOVE_RESTAURANT_MENU';

/**
 * Journey / Itinerary
 */
export const GET_JOURNEY_DATA = 'GET_JOURNEY_DATA';
export const GET_JOURNEY_REVIEW = 'GET_JOURNEY_REVIEW';
export const REMOVE_ITINERARY = 'REMOVE_ITINERARY';

/**
 * Ticket
 */
export const GET_TICKET_DATA = 'GET_TICKET_DATA';
export const GET_TICKET_BY_SKU = 'GET_TICKET_BY_SKU';
export const GET_TICKET_BY_MERCHANT = 'GET_TICKET_BY_MERCHANT';
export const GET_TICKET_RESTAURANT = 'GET_TICKET_RESTAURANT';
export const GET_TICKET_JOURNEY = 'GET_TICKET_JOURNEY';
export const GET_TICKET_HOTEL = 'GET_TICKET_HOTEL';
export const REMOVE_TICKET = 'REMOVE_TICKET';

/**
 * Gallery
 */
export const GET_GALLERY_DATA = 'GET_GALLERY_DATA';
export const REMOVE_GALLERY_PHOTO = 'REMOVE_GALLERY_PHOTO';

/**
 * Tour Guide
 */
export const GET_TOUR_GUIDE_DATA = 'GET_TOUR_GUIDE_DATA';
export const GET_TOUR_GUIDE_DATA_BY_SKU = 'GET_TOUR_GUIDE_DATA_BY_SKU';
export const REMOVE_TOUR_GUIDE = 'REMOVE_TOUR_GUIDE';
